# Generated by Django 4.0.5 on 2024-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название Теста')),
                ('topic', models.CharField(max_length=120, verbose_name='Тема')),
                ('numbers_of_questions', models.IntegerField(verbose_name='Количества Вопросов')),
                ('time', models.IntegerField(help_text='Продолжительность Тестирования в Минутах', verbose_name='Длительность Теста')),
                ('required_score_to_pass', models.IntegerField(help_text='Требуемый Бал в %', verbose_name='Бал для Прохождения')),
                ('difficulty', models.CharField(choices=[('easy', 'лёгкий'), ('medium', 'средний'), ('hard', 'сложный')], max_length=6, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
